services:
  - type: web
    name: f1-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://f1-gp-predictor.netlify.app
      - key: FASTF1_CACHE_DIR
        value: /app/fastf1_cache
